# Identifier
name: semgrep

# Version
version: '1.1'

# Base snap
base: core22

# Maturity, either devel or stable
grade: stable

# Minimal access level, with permissions provided by the interfaces above
confinement: strict

# Build and run architectures
architectures:
  - build-on: [amd64]
  - build-on: [arm64]

# A Python part for "proxying" the wheel from PyPi
parts:
  semgrep:
    plugin: python
    source: .
    python-packages:
      - semgrep

# Apps, aka entry points in the snap
# 
# The following plugs are used:
# 1. Home directory access
# 2. Network access: Semgrep communicated with its Registry to fetch rules. In
#                    addition, version checking and pseudonymous usage metrics
#                    are enabled by default and require Internet access. More
#                    details can be found on the above link: https://semgrep\
#                    .dev/docs/faq/#what-network-requests-are-made
apps:
  semgrep:
    command: bin/python3 -m semgrep
    plugs:
      - home
      - network

# Name displayed in the software center GUI
title: Semgrep

# Sentence summarising the snap
summary: Static code scanning

# Detailed 
description: |
  Semgrep is a fast, open-source, static analysis engine for finding bugs,
  detecting vulnerabilities in third-party dependencies, and enforcing code
  standards. Semgrep analyzes code locally on your computer or in your build
  environment: code is never uploaded.

# Icon displayed in the store
icon: images/icon.png

# Issue reporting
issues:
  - https://github.com/iosifache/semgrep-snap/issues
  - https://github.com/returntocorp/semgrep/issues

# Snap's license (not Semgrep's one, which is LGPL-2.1)
license: MIT

# Website
website: https://github.com/iosifache/semgrep-snap
